/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Juan
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    private List<JTextField> numero;
    private List<JLabel> etiquetas;
    private List<JComboBox> opera;
    private List<JComboBox> operador;
    private List<JTextField>numero1;
    private List<JLabel> etiquetas1;
    
    private List<JButton> boton;
    private int var;
    private char []variable = {'A','B','C','D','E','F','G','H','I','J'};
    private int []numz;
    private int indice;
    private int [][]numec;
    
    public interfaz() {
        initComponents();
        etiquetas = new ArrayList<>();
        opera =  new ArrayList<>();
        operador =  new ArrayList<>();
        numero = new ArrayList<>();
        numero1 = new ArrayList<>();
        etiquetas1 = new ArrayList<>();
        indice=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Variables = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Panel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de ecuaciones");

        Variables.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "2", "5", "6", "7", "8", "9", "10" }));
        Variables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariablesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel2.setText("Z");

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel3.setText("=");

        panel.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(panel);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan\\Desktop\\memoria\\5to semestre\\METODOS\\Programa\\metodos\\imagenes\\ok1.fw.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Restricciones");

        Panel2.setLayout(new java.awt.GridLayout());
        jScrollPane2.setViewportView(Panel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "≤", "≥" }));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan\\Desktop\\memoria\\5to semestre\\METODOS\\Programa\\metodos\\imagenes\\mas.fw.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        panel3.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane3.setViewportView(panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(35, 35, 35)
                                        .addComponent(Variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VariablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariablesActionPerformed
        // TODO add your handling code here:
        panel.removeAll(); 
        panel.repaint(); 
        Panel2.removeAll(); 
        Panel2.repaint(); 
        var = Integer.parseInt(Variables.getSelectedItem().toString());
        //System.out.println(var);
        for (int i=0; i<var; i++){
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            modelo.addElement("+");
            modelo.addElement("-"); 
            JComboBox signo = new JComboBox(modelo);
            panel.add(signo);
            opera.add(signo);
            //------
            JComboBox signo1 = new JComboBox(modelo);
            Panel2.add(signo1);
            operador.add(signo1);
            //String operacion = opera.getSelectedItem().toString();
            JTextField texto = new JTextField();
            //System.out.println(texto);
            //System.out.println(num);
            panel.add(texto);
            numero.add(texto);
            //------
            JTextField texto1 = new JTextField();
            Panel2.add(texto1);
            numero1.add(texto1);
            //------
            JLabel label = new JLabel();
            label.setText(variable[i]+".");
            label.setVisible(true);
            panel.add(label);
            etiquetas.add(label);
            //--
            JLabel label1 = new JLabel();
            label1.setText(variable[i]+".");
            Panel2.add(label1);
            etiquetas1.add(label1);
            //--
            //System.out.print(variable[i]);
            panel.updateUI();
            Panel2.updateUI();
        }
    }//GEN-LAST:event_VariablesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        numz = new int[var];
        int i=0;
        for (JTextField numr : numero){ //for para obtener los numeros 
            numz[i]= Integer.parseInt(numr.getText());
            //System.out.println(numbers[i]);
            i++;
        } 
        i=0;
        for (JComboBox sig : opera){ //for para obetener los signos 
            //System.out.println(sig.getSelectedItem().toString());
            if (sig.getSelectedItem().toString()=="-")
                numz[i]=numz[i]*(-1);
            //System.out.println(numbers[i]);
            i++;
        }
        StringBuffer ecuacion = new StringBuffer();
        int aux =0;
        for (i=0;i<var ; i++){
            if (numz[i]>0){
                if (aux!=0)
                    ecuacion.append(String.valueOf("+"+numz[i])+variable[i]);
                aux++;
            }
            if (numz[i]<0 || aux==1){
                ecuacion.append(String.valueOf(numz[i])+variable[i]);
                aux+=2;
            }
        }
        System.out.println(ecuacion);
        panel.removeAll(); 
        panel.repaint();
        JLabel label = new JLabel();
        label.setText(ecuacion.toString());
        label.setVisible(true);
        panel.add(label);
        etiquetas.add(label);
        //JButton editar = new JButton("Editar");
        //editar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan\\Desktop\\memoria\\5to semestre\\METODOS\\Programa\\metodos\\imagenes\\ok1.fw.png")); 
        //panel.add(editar);
        panel.updateUI();
        jButton1.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        numec = new int[20][20];
        int i=0;
        for (JTextField numr : numero1){ //for para obtener los numeros
            numec[indice][i]= Integer.parseInt(numr.getText());
            //System.out.println(numbers[i]);
            i++;
            System.out.println(i);
        } 
        i=0;
        for (JComboBox sig : operador){ //for para obetener los signos 
            //System.out.println(sig.getSelectedItem().toString());
            if (sig.getSelectedItem().toString()=="-")
                numec[indice][i]=numec[indice][i]*(-1);
            //System.out.println(numbers[i]);
            i++;
        }
        StringBuffer ecuacion = new StringBuffer();
        int aux=0;
        for (i=0;i<var ; i++){
            if (numec[indice][i]>0){
                if (aux!=0)
                    ecuacion.append(String.valueOf("+"+numec[indice][i])+variable[i]);
                aux++;
            }
            if (numec[indice][i]<0 || aux==1){
                ecuacion.append(String.valueOf(numec[indice][i])+variable[i]);
                aux+=2;
            }
            operador.remove(0);
            numero1.remove(0);
            //operador.remove(i);
            //numero1.remove(i);
        }
        ecuacion.append(jComboBox1.getSelectedItem().toString()+jTextField1.getText());
        System.out.println(ecuacion);
        Panel2.removeAll(); 
        Panel2.repaint(); 
        jTextField1.setText(null);
        //var = Integer.parseInt(Variables.getSelectedItem().toString());
        //System.out.println(var);
        for (int x=0; x<var; x++){
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            modelo.addElement("+");
            modelo.addElement("-"); 
            JComboBox signo1 = new JComboBox(modelo);
            Panel2.add(signo1);
            operador.add(signo1);
            JTextField texto1 = new JTextField();
            Panel2.add(texto1);
            numero1.add(texto1);
            JLabel label1 = new JLabel();
            label1.setText(variable[x]+".");
            Panel2.add(label1);
            etiquetas1.add(label1);
            Panel2.updateUI();
        }
        JLabel label = new JLabel();
        label.setText(ecuacion.toString());
        label.setVisible(true);
        panel3.add(label);
        //etiquetas.add(label);
        //JButton editar = new JButton("Editar");
        //editar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan\\Desktop\\memoria\\5to semestre\\METODOS\\Programa\\metodos\\imagenes\\ok1.fw.png")); 
        //panel.add(editar);
        panel3.updateUI();
        indice++;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel2;
    private javax.swing.JComboBox Variables;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel3;
    // End of variables declaration//GEN-END:variables
}
